apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-datapv-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 2Gi